version: "3"
services:
  kali:
    image: sneakykali
    container_name: sneakybeagle
    restart: always
    build:
      context: ./kali
      args:
        SSHPASSWORD: ${SSHPASSWORD}
    ports:
      - "${SSHHOSTPORT}:22"
  nessus:
    image: sneakynessus
    container_name: nessus
    network_mode: "bridge"
    restart: always
    build:
      context: ./nessus
      args:
        ACTIVATION_CODE: ${ACTIVATION_CODE}
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    ports:
      - "${NESSUSHOSTPORT}:8843"